name: Deploy Frontend to Netlify

on:
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: .env ファイルを作成
        run: |
          echo "VITE_RAILS_BACKEND_URL=${{ secrets.VITE_RAILS_BACKEND_URL }}" >> .env
          echo "VITE_REMBG_BACKEND_URL=${{ secrets.VITE_REMBG_BACKEND_URL }}" >> .env

      - name: Netlify にデプロイ
        run: |
          npm install -g netlify-cli
          npm i && npm run build
          netlify deploy --prod --dir=build --auth=$NETLIFY_AUTH_TOKEN --site=$NETLIFY_SITE_ID
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
